global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_services'
    static_configs:
      - targets: ['auth-service:3001','order-service:3002','product-service:3003','inventory-service:3004','delivery-service:3005','warehouse-service:3006','notification_service:3008']
